//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Track_ShuttleRun {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Track_ShuttleRun.WinFormString", typeof(WinFormString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant.
        /// </summary>
        internal static string Antenna {
            get {
                return ResourceManager.GetString("Antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataLen.
        /// </summary>
        internal static string DataLen {
            get {
                return ResourceManager.GetString("DataLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC.
        /// </summary>
        internal static string EPC {
            get {
                return ResourceManager.GetString("EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq(MHz).
        /// </summary>
        internal static string Freq {
            get {
                return ResourceManager.GetString("Freq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get And Clear Buffer.
        /// </summary>
        internal static string GetAndClearBuffer {
            get {
                return ResourceManager.GetString("GetAndClearBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Buffer.
        /// </summary>
        internal static string GetBuffer {
            get {
                return ResourceManager.GetString("GetBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Buffer.
        /// </summary>
        internal static string GettingBuffer {
            get {
                return ResourceManager.GetString("GettingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventorying.
        /// </summary>
        internal static string Inventorying {
            get {
                return ResourceManager.GetString("Inventorying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ncDescription {
            get {
                return ResourceManager.GetString("ncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string ncIp {
            get {
                return ResourceManager.GetString("ncIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac.
        /// </summary>
        internal static string ncMac {
            get {
                return ResourceManager.GetString("ncMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string ncMask {
            get {
                return ResourceManager.GetString("ncMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a netcard first.
        /// </summary>
        internal static string nNoNetCardSelect {
            get {
                return ResourceManager.GetString("nNoNetCardSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChipVer.
        /// </summary>
        internal static string npChipVer {
            get {
                return ResourceManager.GetString("npChipVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string npDefault {
            get {
                return ResourceManager.GetString("npDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceIp.
        /// </summary>
        internal static string npDeviceIp {
            get {
                return ResourceManager.GetString("npDeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceMac.
        /// </summary>
        internal static string npDeviceMac {
            get {
                return ResourceManager.GetString("npDeviceMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string npDeviceName {
            get {
                return ResourceManager.GetString("npDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string npGet {
            get {
                return ResourceManager.GetString("npGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PcMac.
        /// </summary>
        internal static string npPcMac {
            get {
                return ResourceManager.GetString("npPcMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string npReset {
            get {
                return ResourceManager.GetString("npReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string npRetry {
            get {
                return ResourceManager.GetString("npRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string npSave {
            get {
                return ResourceManager.GetString("npSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching NetPort.
        /// </summary>
        internal static string npSearchingNetPort {
            get {
                return ResourceManager.GetString("npSearchingNetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search NetPort.
        /// </summary>
        internal static string npSearchNetPort {
            get {
                return ResourceManager.GetString("npSearchNetPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessCount.
        /// </summary>
        internal static string opSuccessCount {
            get {
                return ResourceManager.GetString("opSuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        internal static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags/sec.
        /// </summary>
        internal static string PerSec {
            get {
                return ResourceManager.GetString("PerSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadCount.
        /// </summary>
        internal static string ReadCount {
            get {
                return ResourceManager.GetString("ReadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rssi(dBm).
        /// </summary>
        internal static string Rssi {
            get {
                return ResourceManager.GetString("Rssi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartInventory {
            get {
                return ResourceManager.GetString("StartInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopInventory {
            get {
                return ResourceManager.GetString("StopInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string tagmask_Action {
            get {
                return ResourceManager.GetString("tagmask_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Len(Hex bit).
        /// </summary>
        internal static string tagmask_MaskLen {
            get {
                return ResourceManager.GetString("tagmask_MaskLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask No.
        /// </summary>
        internal static string tagmask_MaskNo {
            get {
                return ResourceManager.GetString("tagmask_MaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Value.
        /// </summary>
        internal static string tagmask_MaskValue {
            get {
                return ResourceManager.GetString("tagmask_MaskValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemBank.
        /// </summary>
        internal static string tagmask_MemBank {
            get {
                return ResourceManager.GetString("tagmask_MemBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ID.
        /// </summary>
        internal static string tagmask_SessionID {
            get {
                return ResourceManager.GetString("tagmask_SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Addr(Hex bit).
        /// </summary>
        internal static string tagmask_StartAddr {
            get {
                return ResourceManager.GetString("tagmask_StartAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncate.
        /// </summary>
        internal static string tagmask_Truncate {
            get {
                return ResourceManager.GetString("tagmask_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockWrite.
        /// </summary>
        internal static string tipBlockWrite {
            get {
                return ResourceManager.GetString("tipBlockWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearTagMask.
        /// </summary>
        internal static string tipClearTagMask {
            get {
                return ResourceManager.GetString("tipClearTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Reader.
        /// </summary>
        internal static string tipConnect {
            get {
                return ResourceManager.GetString("tipConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Failed, Cause.
        /// </summary>
        internal static string tipConnectFailedCause {
            get {
                return ResourceManager.GetString("tipConnectFailedCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Target And Session Inventory.
        /// </summary>
        internal static string tipCustomizeTargetSessionInventory {
            get {
                return ResourceManager.GetString("tipCustomizeTargetSessionInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data export successful.
        /// </summary>
        internal static string tipDataExportSuccess {
            get {
                return ResourceManager.GetString("tipDataExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input 8 Bytes string at least.
        /// </summary>
        internal static string tipEightBytesAtLeast {
            get {
                return ResourceManager.GetString("tipEightBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string is invalid.
        /// </summary>
        internal static string tipEmptyString {
            get {
                return ResourceManager.GetString("tipEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute success.
        /// </summary>
        internal static string tipExecSuccess {
            get {
                return ResourceManager.GetString("tipExecSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed, Cause .
        /// </summary>
        internal static string tipFailedCause {
            get {
                return ResourceManager.GetString("tipFailedCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastSwitch Inventory.
        /// </summary>
        internal static string tipFastSwitch {
            get {
                return ResourceManager.GetString("tipFastSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input 4 Bytes string at least.
        /// </summary>
        internal static string tipFourBytesAtLeast {
            get {
                return ResourceManager.GetString("tipFourBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum range does not conform to the specification, please refer to the communication protocol.
        /// </summary>
        internal static string tipFreqNotInRegion {
            get {
                return ResourceManager.GetString("tipFreqNotInRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAccessEpcMatch.
        /// </summary>
        internal static string tipGetAccessEpcMatch {
            get {
                return ResourceManager.GetString("tipGetAccessEpcMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAndResetInventoryBuffer.
        /// </summary>
        internal static string tipGetAndResetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipGetAndResetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAntDetector.
        /// </summary>
        internal static string tipGetAntDetector {
            get {
                return ResourceManager.GetString("tipGetAntDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDrmMode.
        /// </summary>
        internal static string tipGetDrmMode {
            get {
                return ResourceManager.GetString("tipGetDrmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFirmwareVersion.
        /// </summary>
        internal static string tipGetFirmwareVersion {
            get {
                return ResourceManager.GetString("tipGetFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFrequencyRegion.
        /// </summary>
        internal static string tipGetFrequencyRegion {
            get {
                return ResourceManager.GetString("tipGetFrequencyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetImpedanceMatch.
        /// </summary>
        internal static string tipGetImpedanceMatch {
            get {
                return ResourceManager.GetString("tipGetImpedanceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInternalVersion.
        /// </summary>
        internal static string tipGetInternalVersion {
            get {
                return ResourceManager.GetString("tipGetInternalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInventoryBuffer.
        /// </summary>
        internal static string tipGetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipGetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInventoryBufferTagCount.
        /// </summary>
        internal static string tipGetInventoryBufferTagCount {
            get {
                return ResourceManager.GetString("tipGetInventoryBufferTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMonzaStatus.
        /// </summary>
        internal static string tipGetMonzaStatus {
            get {
                return ResourceManager.GetString("tipGetMonzaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOutputPower.
        /// </summary>
        internal static string tipGetOutputPower {
            get {
                return ResourceManager.GetString("tipGetOutputPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProfile.
        /// </summary>
        internal static string tipGetProfile {
            get {
                return ResourceManager.GetString("tipGetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReaderAntGroup.
        /// </summary>
        internal static string tipGetReaderAntGroup {
            get {
                return ResourceManager.GetString("tipGetReaderAntGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReaderIdentifier.
        /// </summary>
        internal static string tipGetReaderIdentifier {
            get {
                return ResourceManager.GetString("tipGetReaderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReaderTemperature.
        /// </summary>
        internal static string tipGetReaderTemperature {
            get {
                return ResourceManager.GetString("tipGetReaderTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTagMask.
        /// </summary>
        internal static string tipGetTagMask {
            get {
                return ResourceManager.GetString("tipGetTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetWorkAntenna.
        /// </summary>
        internal static string tipGetWorkAntenna {
            get {
                return ResourceManager.GetString("tipGetWorkAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have not match.
        /// </summary>
        internal static string tipHaveNoMatch {
            get {
                return ResourceManager.GetString("tipHaveNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have not yet selected a tag.
        /// </summary>
        internal static string tipHaveNotYetSelectedTag {
            get {
                return ResourceManager.GetString("tipHaveNotYetSelectedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP CLIENT mode, module Keep Alive, can detect when the device is disconnected.
        /// </summary>
        internal static string tipHeartbeatEn {
            get {
                return ResourceManager.GetString("tipHeartbeatEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port negotiation configuration Enable.
        /// </summary>
        internal static string tipHwCfgComCfgEn {
            get {
                return ResourceManager.GetString("tipHwCfgComCfgEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhcp Enable.
        /// </summary>
        internal static string tipHwCfgDhcpEn {
            get {
                return ResourceManager.GetString("tipHwCfgDhcpEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string tipInvalidParameter {
            get {
                return ResourceManager.GetString("tipInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Inventory.
        /// </summary>
        internal static string tipInventory {
            get {
                return ResourceManager.GetString("tipInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory 6B Tag.
        /// </summary>
        internal static string tipInventory6B {
            get {
                return ResourceManager.GetString("tipInventory6B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealTime Inventory.
        /// </summary>
        internal static string tipInventoryReal {
            get {
                return ResourceManager.GetString("tipInventoryReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillTag.
        /// </summary>
        internal static string tipKillTag {
            get {
                return ResourceManager.GetString("tipKillTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock 6B Tag.
        /// </summary>
        internal static string tipLock6BTag {
            get {
                return ResourceManager.GetString("tipLock6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockTag.
        /// </summary>
        internal static string tipLockTag {
            get {
                return ResourceManager.GetString("tipLockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no tag mask found.
        /// </summary>
        internal static string tipNoTagMask {
            get {
                return ResourceManager.GetString("tipNoTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network disconnection: close the connection.
        /// </summary>
        internal static string tipPhyDisconnect {
            get {
                return ResourceManager.GetString("tipPhyDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query 6B Tag.
        /// </summary>
        internal static string tipQuery6BTag {
            get {
                return ResourceManager.GetString("tipQuery6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use random local port in tcp client mode.
        /// </summary>
        internal static string tipRandEn {
            get {
                return ResourceManager.GetString("tipRandEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read 6B Tag.
        /// </summary>
        internal static string tipRead6BTag {
            get {
                return ResourceManager.GetString("tipRead6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadGpioValue.
        /// </summary>
        internal static string tipReadGpioValue {
            get {
                return ResourceManager.GetString("tipReadGpioValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadTag.
        /// </summary>
        internal static string tipReadTag {
            get {
                return ResourceManager.GetString("tipReadTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect Success.
        /// </summary>
        internal static string tipReconnectSuccess {
            get {
                return ResourceManager.GetString("tipReconnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When network connection: clear serial port data.
        /// </summary>
        internal static string tipResetCtrl {
            get {
                return ResourceManager.GetString("tipResetCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetInventoryBuffer.
        /// </summary>
        internal static string tipResetInventoryBuffer {
            get {
                return ResourceManager.GetString("tipResetInventoryBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Reader.
        /// </summary>
        internal static string tipResetReader {
            get {
                return ResourceManager.GetString("tipResetReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a membank to lock.
        /// </summary>
        internal static string tipSelectLockBank {
            get {
                return ResourceManager.GetString("tipSelectLockBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select lockType.
        /// </summary>
        internal static string tipSelectLockType {
            get {
                return ResourceManager.GetString("tipSelectLockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a membank first.
        /// </summary>
        internal static string tipSelectMemBank {
            get {
                return ResourceManager.GetString("tipSelectMemBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAccessEpcMatch.
        /// </summary>
        internal static string tipSetAccessEpcMatch {
            get {
                return ResourceManager.GetString("tipSetAccessEpcMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAntDetector.
        /// </summary>
        internal static string tipSetAntDetector {
            get {
                return ResourceManager.GetString("tipSetAntDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBeeperMode.
        /// </summary>
        internal static string tipSetBeeperMode {
            get {
                return ResourceManager.GetString("tipSetBeeperMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetFrequencyRegion.
        /// </summary>
        internal static string tipSetFrequencyRegion {
            get {
                return ResourceManager.GetString("tipSetFrequencyRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetImpedanceMatch.
        /// </summary>
        internal static string tipSetImpedanceMatch {
            get {
                return ResourceManager.GetString("tipSetImpedanceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMonzaStatus.
        /// </summary>
        internal static string tipSetMonzaStatus {
            get {
                return ResourceManager.GetString("tipSetMonzaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetOutputPower.
        /// </summary>
        internal static string tipSetOutputPower {
            get {
                return ResourceManager.GetString("tipSetOutputPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProfile.
        /// </summary>
        internal static string tipSetProfile {
            get {
                return ResourceManager.GetString("tipSetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetReadAddress.
        /// </summary>
        internal static string tipSetReadAddress {
            get {
                return ResourceManager.GetString("tipSetReadAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetReaderAntGroup.
        /// </summary>
        internal static string tipSetReaderAntGroup {
            get {
                return ResourceManager.GetString("tipSetReaderAntGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetReaderIdentifier.
        /// </summary>
        internal static string tipSetReaderIdentifier {
            get {
                return ResourceManager.GetString("tipSetReaderIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTagMask.
        /// </summary>
        internal static string tipSetTagMask {
            get {
                return ResourceManager.GetString("tipSetTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTempOutpower.
        /// </summary>
        internal static string tipSetTempOutpower {
            get {
                return ResourceManager.GetString("tipSetTempOutpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetUartBaudrate.
        /// </summary>
        internal static string tipSetUartBaudrate {
            get {
                return ResourceManager.GetString("tipSetUartBaudrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWorkAntenna.
        /// </summary>
        internal static string tipSetWorkAntenna {
            get {
                return ResourceManager.GetString("tipSetWorkAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Inventory.
        /// </summary>
        internal static string tipStopInventory {
            get {
                return ResourceManager.GetString("tipStopInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, use S1 mode inventory, which applies to most of the Impinj tags.
        /// </summary>
        internal static string tipTagFocus {
            get {
                return ResourceManager.GetString("tipTagFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagMask.
        /// </summary>
        internal static string tipTagMask {
            get {
                return ResourceManager.GetString("tipTagMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The byte is already locked.
        /// </summary>
        internal static string tipThisByteIsAlreadyLocked {
            get {
                return ResourceManager.GetString("tipThisByteIsAlreadyLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This byte is not locked.
        /// </summary>
        internal static string tipThisByteIsNotLocked {
            get {
                return ResourceManager.GetString("tipThisByteIsNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input 12 Bytes string at least.
        /// </summary>
        internal static string tipTwelveBytesAtLeast {
            get {
                return ResourceManager.GetString("tipTwelveBytesAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Error.
        /// </summary>
        internal static string tipUnknowError {
            get {
                return ResourceManager.GetString("tipUnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write 6B Tag.
        /// </summary>
        internal static string tipWrite6BTag {
            get {
                return ResourceManager.GetString("tipWrite6BTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteGpioValue.
        /// </summary>
        internal static string tipWriteGpioValue {
            get {
                return ResourceManager.GetString("tipWriteGpioValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteTag.
        /// </summary>
        internal static string tipWriteTag {
            get {
                return ResourceManager.GetString("tipWriteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip addr error, eg: 192.168.8.168.
        /// </summary>
        internal static string tWrongIpAddr {
            get {
                return ResourceManager.GetString("tWrongIpAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac adrr error, eg: 12:34:56:AB:CD:EF.
        /// </summary>
        internal static string tWrongMacAddr {
            get {
                return ResourceManager.GetString("tWrongMacAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Power.
        /// </summary>
        internal static string useCmd8A25 {
            get {
                return ResourceManager.GetString("useCmd8A25", resourceCulture);
            }
        }
    }
}
